name: vyral
description: A Flutter social networking application
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Navigation
  go_router: ^15.1.2

  # Network
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # WebSocket
  web_socket_channel: ^3.0.3
  socket_io_client: ^3.1.2

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0-beta.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI
  cached_network_image: ^3.3.1
  image_picker: ^1.0.4
  flutter_svg: ^2.0.9
  lottie: ^3.3.1
  shimmer: ^3.0.0

  # Utils
  intl: ^0.20.2
  connectivity_plus: ^6.1.4
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0

  # Push Notifications
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1

  # Media
  video_player: ^2.8.1
  photo_view: ^0.15.0

  # Development
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^9.2.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
